[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
num = "0.4.1"
pathfinding = "4.6.0"
regex = "1.10.2"

[build-dependencies]
regex = "1.10.2"
